[project]
name = "threshold-buffer"
authors = ["Threshold Systems"]
description = "A dynamic threshold management and buffer system for blockchain applications"
telemetry = false
requirements = []

[contracts.buffer-core]
path = "contracts/buffer-core.clar"
depends_on = []

[contracts.reward-mechanism]
path = "contracts/reward-mechanism.clar"
depends_on = []

[contracts.threshold-registry]
path = "contracts/threshold-registry.clar"
depends_on = []

[contracts.validator-core]
path = "contracts/validator-core.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
